export type CountryConfig = {
  name: string
  locale: string
  phonePrefix: string
  phonePattern: string
}

// Comprehensive list of 200+ countries with best-matching Faker locale
export const countryConfigs: Record<string, CountryConfig> = {
  AF: { name: 'Afghanistan', locale: 'fa', phonePrefix: '+93', phonePattern: '7########' },
  AL: { name: 'Albania', locale: 'en', phonePrefix: '+355', phonePattern: '6########' },
  DZ: { name: 'Algeria', locale: 'ar', phonePrefix: '+213', phonePattern: '5########' },
  AD: { name: 'Andorra', locale: 'es', phonePrefix: '+376', phonePattern: '######' },
  AO: { name: 'Angola', locale: 'pt_PT', phonePrefix: '+244', phonePattern: '9########' },
  AG: { name: 'Antigua and Barbuda', locale: 'en', phonePrefix: '+1268', phonePattern: '#######' },
  AR: { name: 'Argentina', locale: 'es', phonePrefix: '+54', phonePattern: '11########' },
  AM: { name: 'Armenia', locale: 'hy', phonePrefix: '+374', phonePattern: '9#######' },
  AU: { name: 'Australia', locale: 'en_AU', phonePrefix: '+61', phonePattern: '4########' },
  AT: { name: 'Austria', locale: 'de_AT', phonePrefix: '+43', phonePattern: '6########' },
  AZ: { name: 'Azerbaijan', locale: 'az', phonePrefix: '+994', phonePattern: '5#######' },
  BS: { name: 'Bahamas', locale: 'en', phonePrefix: '+1242', phonePattern: '#######' },
  BH: { name: 'Bahrain', locale: 'ar', phonePrefix: '+973', phonePattern: '3#######' },
  BD: { name: 'Bangladesh', locale: 'en', phonePrefix: '+880', phonePattern: '1#########' },
  BB: { name: 'Barbados', locale: 'en', phonePrefix: '+1246', phonePattern: '#######' },
  BY: { name: 'Belarus', locale: 'ru', phonePrefix: '+375', phonePattern: '29#######' },
  BE: { name: 'Belgium', locale: 'fr_BE', phonePrefix: '+32', phonePattern: '4########' },
  BZ: { name: 'Belize', locale: 'en', phonePrefix: '+501', phonePattern: '6######' },
  BJ: { name: 'Benin', locale: 'fr', phonePrefix: '+229', phonePattern: '9#######' },
  BT: { name: 'Bhutan', locale: 'en', phonePrefix: '+975', phonePattern: '17######' },
  BO: { name: 'Bolivia', locale: 'es', phonePrefix: '+591', phonePattern: '7#######' },
  BA: { name: 'Bosnia and Herzegovina', locale: 'hr', phonePrefix: '+387', phonePattern: '6#######' },
  BW: { name: 'Botswana', locale: 'en', phonePrefix: '+267', phonePattern: '7#######' },
  BR: { name: 'Brazil', locale: 'pt_BR', phonePrefix: '+55', phonePattern: '119########' },
  BN: { name: 'Brunei', locale: 'en', phonePrefix: '+673', phonePattern: '8######' },
  BG: { name: 'Bulgaria', locale: 'en', phonePrefix: '+359', phonePattern: '8########' },
  BF: { name: 'Burkina Faso', locale: 'fr', phonePrefix: '+226', phonePattern: '7#######' },
  BI: { name: 'Burundi', locale: 'fr', phonePrefix: '+257', phonePattern: '7#######' },
  CV: { name: 'Cabo Verde', locale: 'pt_PT', phonePrefix: '+238', phonePattern: '9######' },
  KH: { name: 'Cambodia', locale: 'en', phonePrefix: '+855', phonePattern: '9########' },
  CM: { name: 'Cameroon', locale: 'fr', phonePrefix: '+237', phonePattern: '6########' },
  CA: { name: 'Canada', locale: 'en_CA', phonePrefix: '+1', phonePattern: '##########' },
  CF: { name: 'Central African Republic', locale: 'fr', phonePrefix: '+236', phonePattern: '7#######' },
  TD: { name: 'Chad', locale: 'fr', phonePrefix: '+235', phonePattern: '6#######' },
  CL: { name: 'Chile', locale: 'es', phonePrefix: '+56', phonePattern: '9########' },
  CN: { name: 'China', locale: 'zh_CN', phonePrefix: '+86', phonePattern: '1##########' },
  CO: { name: 'Colombia', locale: 'es', phonePrefix: '+57', phonePattern: '3#########' },
  KM: { name: 'Comoros', locale: 'fr', phonePrefix: '+269', phonePattern: '3######' },
  CG: { name: 'Congo', locale: 'fr', phonePrefix: '+242', phonePattern: '0########' },
  CD: { name: 'DR Congo', locale: 'fr', phonePrefix: '+243', phonePattern: '8########' },
  CR: { name: 'Costa Rica', locale: 'es', phonePrefix: '+506', phonePattern: '8#######' },
  CI: { name: "Côte d'Ivoire", locale: 'fr', phonePrefix: '+225', phonePattern: '0#########' },
  HR: { name: 'Croatia', locale: 'hr', phonePrefix: '+385', phonePattern: '9########' },
  CU: { name: 'Cuba', locale: 'es', phonePrefix: '+53', phonePattern: '5#######' },
  CY: { name: 'Cyprus', locale: 'el', phonePrefix: '+357', phonePattern: '9#######' },
  CZ: { name: 'Czech Republic', locale: 'cs_CZ', phonePrefix: '+420', phonePattern: '7########' },
  DK: { name: 'Denmark', locale: 'da', phonePrefix: '+45', phonePattern: '########' },
  DJ: { name: 'Djibouti', locale: 'fr', phonePrefix: '+253', phonePattern: '77######' },
  DM: { name: 'Dominica', locale: 'en', phonePrefix: '+1767', phonePattern: '#######' },
  DO: { name: 'Dominican Republic', locale: 'es', phonePrefix: '+1809', phonePattern: '#######' },
  EC: { name: 'Ecuador', locale: 'es', phonePrefix: '+593', phonePattern: '9########' },
  EG: { name: 'Egypt', locale: 'ar', phonePrefix: '+20', phonePattern: '1#########' },
  SV: { name: 'El Salvador', locale: 'es', phonePrefix: '+503', phonePattern: '7#######' },
  GQ: { name: 'Equatorial Guinea', locale: 'es', phonePrefix: '+240', phonePattern: '2########' },
  ER: { name: 'Eritrea', locale: 'en', phonePrefix: '+291', phonePattern: '7######' },
  EE: { name: 'Estonia', locale: 'en', phonePrefix: '+372', phonePattern: '5#######' },
  SZ: { name: 'Eswatini', locale: 'en', phonePrefix: '+268', phonePattern: '7########' },
  ET: { name: 'Ethiopia', locale: 'en', phonePrefix: '+251', phonePattern: '9########' },
  FJ: { name: 'Fiji', locale: 'en', phonePrefix: '+679', phonePattern: '9######' },
  FI: { name: 'Finland', locale: 'fi', phonePrefix: '+358', phonePattern: '4########' },
  FR: { name: 'France', locale: 'fr', phonePrefix: '+33', phonePattern: '6########' },
  GA: { name: 'Gabon', locale: 'fr', phonePrefix: '+241', phonePattern: '0########' },
  GM: { name: 'Gambia', locale: 'en', phonePrefix: '+220', phonePattern: '#######' },
  GE: { name: 'Georgia', locale: 'ka_GE', phonePrefix: '+995', phonePattern: '5########' },
  DE: { name: 'Germany', locale: 'de', phonePrefix: '+49', phonePattern: '1##########' },
  GH: { name: 'Ghana', locale: 'en_GH', phonePrefix: '+233', phonePattern: '2#########' },
  GR: { name: 'Greece', locale: 'el', phonePrefix: '+30', phonePattern: '6#########' },
  GD: { name: 'Grenada', locale: 'en', phonePrefix: '+1473', phonePattern: '#######' },
  GT: { name: 'Guatemala', locale: 'es', phonePrefix: '+502', phonePattern: '########' },
  GN: { name: 'Guinea', locale: 'fr', phonePrefix: '+224', phonePattern: '6########' },
  GW: { name: 'Guinea-Bissau', locale: 'pt_PT', phonePrefix: '+245', phonePattern: '9######' },
  GY: { name: 'Guyana', locale: 'en', phonePrefix: '+592', phonePattern: '6######' },
  HT: { name: 'Haiti', locale: 'fr', phonePrefix: '+509', phonePattern: '3#######' },
  HN: { name: 'Honduras', locale: 'es', phonePrefix: '+504', phonePattern: '9#######' },
  HU: { name: 'Hungary', locale: 'hu', phonePrefix: '+36', phonePattern: '20#######' },
  IS: { name: 'Iceland', locale: 'en', phonePrefix: '+354', phonePattern: '#######' },
  IN: { name: 'India', locale: 'en_IN', phonePrefix: '+91', phonePattern: '9#########' },
  ID: { name: 'Indonesia', locale: 'id_ID', phonePrefix: '+62', phonePattern: '8##########' },
  IR: { name: 'Iran', locale: 'fa', phonePrefix: '+98', phonePattern: '9#########' },
  IQ: { name: 'Iraq', locale: 'ar', phonePrefix: '+964', phonePattern: '7#########' },
  IE: { name: 'Ireland', locale: 'en_IE', phonePrefix: '+353', phonePattern: '8########' },
  IL: { name: 'Israel', locale: 'he', phonePrefix: '+972', phonePattern: '5#########' },
  IT: { name: 'Italy', locale: 'it', phonePrefix: '+39', phonePattern: '3#########' },
  JM: { name: 'Jamaica', locale: 'en', phonePrefix: '+1876', phonePattern: '#######' },
  JP: { name: 'Japan', locale: 'ja', phonePrefix: '+81', phonePattern: '9#########' },
  JO: { name: 'Jordan', locale: 'ar', phonePrefix: '+962', phonePattern: '7########' },
  KZ: { name: 'Kazakhstan', locale: 'ru', phonePrefix: '+7', phonePattern: '7#########' },
  KE: { name: 'Kenya', locale: 'en_KE', phonePrefix: '+254', phonePattern: '7########' },
  KI: { name: 'Kiribati', locale: 'en', phonePrefix: '+686', phonePattern: '########' },
  KP: { name: 'North Korea', locale: 'ko', phonePrefix: '+850', phonePattern: '########' },
  KR: { name: 'South Korea', locale: 'ko', phonePrefix: '+82', phonePattern: '10########' },
  KW: { name: 'Kuwait', locale: 'ar', phonePrefix: '+965', phonePattern: '5#######' },
  KG: { name: 'Kyrgyzstan', locale: 'ru', phonePrefix: '+996', phonePattern: '7########' },
  LA: { name: 'Laos', locale: 'en', phonePrefix: '+856', phonePattern: '20########' },
  LV: { name: 'Latvia', locale: 'lv', phonePrefix: '+371', phonePattern: '2#######' },
  LB: { name: 'Lebanon', locale: 'ar', phonePrefix: '+961', phonePattern: '7########' },
  LS: { name: 'Lesotho', locale: 'en', phonePrefix: '+266', phonePattern: '5#######' },
  LR: { name: 'Liberia', locale: 'en', phonePrefix: '+231', phonePattern: '########' },
  LY: { name: 'Libya', locale: 'ar', phonePrefix: '+218', phonePattern: '9#########' },
  LI: { name: 'Liechtenstein', locale: 'de', phonePrefix: '+423', phonePattern: '#######' },
  LT: { name: 'Lithuania', locale: 'en', phonePrefix: '+370', phonePattern: '6#######' },
  LU: { name: 'Luxembourg', locale: 'fr_LU', phonePrefix: '+352', phonePattern: '6########' },
  MG: { name: 'Madagascar', locale: 'fr', phonePrefix: '+261', phonePattern: '3########' },
  MW: { name: 'Malawi', locale: 'en', phonePrefix: '+265', phonePattern: '9########' },
  MY: { name: 'Malaysia', locale: 'en', phonePrefix: '+60', phonePattern: '1#########' },
  MV: { name: 'Maldives', locale: 'en', phonePrefix: '+960', phonePattern: '9######' },
  ML: { name: 'Mali', locale: 'fr', phonePrefix: '+223', phonePattern: '7#######' },
  MT: { name: 'Malta', locale: 'en', phonePrefix: '+356', phonePattern: '9#######' },
  MH: { name: 'Marshall Islands', locale: 'en', phonePrefix: '+692', phonePattern: '#######' },
  MR: { name: 'Mauritania', locale: 'ar', phonePrefix: '+222', phonePattern: '########' },
  MU: { name: 'Mauritius', locale: 'en', phonePrefix: '+230', phonePattern: '5#######' },
  MX: { name: 'Mexico', locale: 'es_MX', phonePrefix: '+52', phonePattern: '1##########' },
  FM: { name: 'Micronesia', locale: 'en', phonePrefix: '+691', phonePattern: '#######' },
  MD: { name: 'Moldova', locale: 'ro_MD', phonePrefix: '+373', phonePattern: '6########' },
  MC: { name: 'Monaco', locale: 'fr', phonePrefix: '+377', phonePattern: '6########' },
  MN: { name: 'Mongolia', locale: 'en', phonePrefix: '+976', phonePattern: '########' },
  ME: { name: 'Montenegro', locale: 'sr_RS_latin', phonePrefix: '+382', phonePattern: '6########' },
  MA: { name: 'Morocco', locale: 'ar', phonePrefix: '+212', phonePattern: '6########' },
  MZ: { name: 'Mozambique', locale: 'pt_PT', phonePrefix: '+258', phonePattern: '8#########' },
  MM: { name: 'Myanmar', locale: 'en', phonePrefix: '+95', phonePattern: '9#########' },
  NA: { name: 'Namibia', locale: 'en', phonePrefix: '+264', phonePattern: '8#######' },
  NR: { name: 'Nauru', locale: 'en', phonePrefix: '+674', phonePattern: '#######' },
  NP: { name: 'Nepal', locale: 'ne', phonePrefix: '+977', phonePattern: '98########' },
  NL: { name: 'Netherlands', locale: 'nl', phonePrefix: '+31', phonePattern: '6########' },
  NZ: { name: 'New Zealand', locale: 'en', phonePrefix: '+64', phonePattern: '2#########' },
  NI: { name: 'Nicaragua', locale: 'es', phonePrefix: '+505', phonePattern: '8#######' },
  NE: { name: 'Niger', locale: 'fr', phonePrefix: '+227', phonePattern: '9#######' },
  NG: { name: 'Nigeria', locale: 'en_NG', phonePrefix: '+234', phonePattern: '8#########' },
  MK: { name: 'North Macedonia', locale: 'mk', phonePrefix: '+389', phonePattern: '7#######' },
  NO: { name: 'Norway', locale: 'nb_NO', phonePrefix: '+47', phonePattern: '9#######' },
  OM: { name: 'Oman', locale: 'ar', phonePrefix: '+968', phonePattern: '9#######' },
  PK: { name: 'Pakistan', locale: 'ur', phonePrefix: '+92', phonePattern: '3#########' },
  PW: { name: 'Palau', locale: 'en', phonePrefix: '+680', phonePattern: '#######' },
  PS: { name: 'Palestine', locale: 'ar', phonePrefix: '+970', phonePattern: '5########' },
  PA: { name: 'Panama', locale: 'es', phonePrefix: '+507', phonePattern: '6#######' },
  PG: { name: 'Papua New Guinea', locale: 'en', phonePrefix: '+675', phonePattern: '7#######' },
  PY: { name: 'Paraguay', locale: 'es', phonePrefix: '+595', phonePattern: '9########' },
  PE: { name: 'Peru', locale: 'es', phonePrefix: '+51', phonePattern: '9########' },
  PH: { name: 'Philippines', locale: 'en', phonePrefix: '+63', phonePattern: '9#########' },
  PL: { name: 'Poland', locale: 'pl', phonePrefix: '+48', phonePattern: '#########' },
  PT: { name: 'Portugal', locale: 'pt_PT', phonePrefix: '+351', phonePattern: '9########' },
  QA: { name: 'Qatar', locale: 'ar', phonePrefix: '+974', phonePattern: '########' },
  RO: { name: 'Romania', locale: 'ro', phonePrefix: '+40', phonePattern: '7########' },
  RU: { name: 'Russia', locale: 'ru', phonePrefix: '+7', phonePattern: '9#########' },
  RW: { name: 'Rwanda', locale: 'en', phonePrefix: '+250', phonePattern: '7########' },
  KN: { name: 'Saint Kitts and Nevis', locale: 'en', phonePrefix: '+1869', phonePattern: '#######' },
  LC: { name: 'Saint Lucia', locale: 'en', phonePrefix: '+1758', phonePattern: '#######' },
  VC: { name: 'Saint Vincent and the Grenadines', locale: 'en', phonePrefix: '+1784', phonePattern: '#######' },
  WS: { name: 'Samoa', locale: 'en', phonePrefix: '+685', phonePattern: '#######' },
  SM: { name: 'San Marino', locale: 'it', phonePrefix: '+378', phonePattern: '########' },
  ST: { name: 'São Tomé and Príncipe', locale: 'pt_PT', phonePrefix: '+239', phonePattern: '9######' },
  SA: { name: 'Saudi Arabia', locale: 'ar', phonePrefix: '+966', phonePattern: '5########' },
  SN: { name: 'Senegal', locale: 'fr_SN', phonePrefix: '+221', phonePattern: '7########' },
  RS: { name: 'Serbia', locale: 'sr_RS_latin', phonePrefix: '+381', phonePattern: '6########' },
  SC: { name: 'Seychelles', locale: 'en', phonePrefix: '+248', phonePattern: '2######' },
  SL: { name: 'Sierra Leone', locale: 'en', phonePrefix: '+232', phonePattern: '########' },
  SG: { name: 'Singapore', locale: 'en', phonePrefix: '+65', phonePattern: '9#######' },
  SK: { name: 'Slovakia', locale: 'sk', phonePrefix: '+421', phonePattern: '9########' },
  SI: { name: 'Slovenia', locale: 'en', phonePrefix: '+386', phonePattern: '########' },
  SB: { name: 'Solomon Islands', locale: 'en', phonePrefix: '+677', phonePattern: '#######' },
  SO: { name: 'Somalia', locale: 'en', phonePrefix: '+252', phonePattern: '6########' },
  ZA: { name: 'South Africa', locale: 'en_ZA', phonePrefix: '+27', phonePattern: '7########' },
  SS: { name: 'South Sudan', locale: 'en', phonePrefix: '+211', phonePattern: '9########' },
  ES: { name: 'Spain', locale: 'es', phonePrefix: '+34', phonePattern: '6########' },
  LK: { name: 'Sri Lanka', locale: 'en', phonePrefix: '+94', phonePattern: '7########' },
  SD: { name: 'Sudan', locale: 'ar', phonePrefix: '+249', phonePattern: '9########' },
  SR: { name: 'Suriname', locale: 'nl', phonePrefix: '+597', phonePattern: '#######' },
  SE: { name: 'Sweden', locale: 'sv', phonePrefix: '+46', phonePattern: '7#########' },
  CH: { name: 'Switzerland', locale: 'de_CH', phonePrefix: '+41', phonePattern: '7########' },
  SY: { name: 'Syria', locale: 'ar', phonePrefix: '+963', phonePattern: '9########' },
  TW: { name: 'Taiwan', locale: 'zh_TW', phonePrefix: '+886', phonePattern: '9########' },
  TJ: { name: 'Tajikistan', locale: 'ru', phonePrefix: '+992', phonePattern: '9########' },
  TZ: { name: 'Tanzania', locale: 'en', phonePrefix: '+255', phonePattern: '7########' },
  TH: { name: 'Thailand', locale: 'th', phonePrefix: '+66', phonePattern: '8########' },
  TL: { name: 'Timor-Leste', locale: 'pt_PT', phonePrefix: '+670', phonePattern: '7#######' },
  TG: { name: 'Togo', locale: 'fr', phonePrefix: '+228', phonePattern: '9#######' },
  TO: { name: 'Tonga', locale: 'en', phonePrefix: '+676', phonePattern: '#######' },
  TT: { name: 'Trinidad and Tobago', locale: 'en', phonePrefix: '+1868', phonePattern: '#######' },
  TN: { name: 'Tunisia', locale: 'ar', phonePrefix: '+216', phonePattern: '########' },
  TR: { name: 'Turkey', locale: 'tr', phonePrefix: '+90', phonePattern: '5#########' },
  TM: { name: 'Turkmenistan', locale: 'ru', phonePrefix: '+993', phonePattern: '6#######' },
  TV: { name: 'Tuvalu', locale: 'en', phonePrefix: '+688', phonePattern: '######' },
  UG: { name: 'Uganda', locale: 'en', phonePrefix: '+256', phonePattern: '7########' },
  UA: { name: 'Ukraine', locale: 'uk', phonePrefix: '+380', phonePattern: '9#########' },
  AE: { name: 'United Arab Emirates', locale: 'en', phonePrefix: '+971', phonePattern: '5########' },
  GB: { name: 'United Kingdom', locale: 'en_GB', phonePrefix: '+44', phonePattern: '7#########' },
  US: { name: 'United States', locale: 'en_US', phonePrefix: '+1', phonePattern: '##########' },
  UY: { name: 'Uruguay', locale: 'es', phonePrefix: '+598', phonePattern: '9########' },
  UZ: { name: 'Uzbekistan', locale: 'ru', phonePrefix: '+998', phonePattern: '9########' },
  VU: { name: 'Vanuatu', locale: 'en', phonePrefix: '+678', phonePattern: '#######' },
  VA: { name: 'Vatican City', locale: 'it', phonePrefix: '+379', phonePattern: '########' },
  VE: { name: 'Venezuela', locale: 'es', phonePrefix: '+58', phonePattern: '4#########' },
  VN: { name: 'Vietnam', locale: 'vi', phonePrefix: '+84', phonePattern: '9########' },
  YE: { name: 'Yemen', locale: 'ar', phonePrefix: '+967', phonePattern: '7########' },
  ZM: { name: 'Zambia', locale: 'en', phonePrefix: '+260', phonePattern: '9########' },
  ZW: { name: 'Zimbabwe', locale: 'en', phonePrefix: '+263', phonePattern: '7########' },
  // Territories & Special Regions
  HK: { name: 'Hong Kong', locale: 'en_HK', phonePrefix: '+852', phonePattern: '9#######' },
  MO: { name: 'Macau', locale: 'zh_CN', phonePrefix: '+853', phonePattern: '6#######' },
  PR: { name: 'Puerto Rico', locale: 'es', phonePrefix: '+1787', phonePattern: '#######' },
  GU: { name: 'Guam', locale: 'en', phonePrefix: '+1671', phonePattern: '#######' },
  VI: { name: 'US Virgin Islands', locale: 'en', phonePrefix: '+1340', phonePattern: '#######' },
  AS: { name: 'American Samoa', locale: 'en', phonePrefix: '+1684', phonePattern: '#######' },
  GI: { name: 'Gibraltar', locale: 'en_GB', phonePrefix: '+350', phonePattern: '########' },
  GL: { name: 'Greenland', locale: 'da', phonePrefix: '+299', phonePattern: '######' },
  FO: { name: 'Faroe Islands', locale: 'da', phonePrefix: '+298', phonePattern: '######' },
  BM: { name: 'Bermuda', locale: 'en', phonePrefix: '+1441', phonePattern: '#######' },
  KY: { name: 'Cayman Islands', locale: 'en', phonePrefix: '+1345', phonePattern: '#######' },
  CW: { name: 'Curaçao', locale: 'nl', phonePrefix: '+599', phonePattern: '9#######' },
  AW: { name: 'Aruba', locale: 'nl', phonePrefix: '+297', phonePattern: '#######' },
  GP: { name: 'Guadeloupe', locale: 'fr', phonePrefix: '+590', phonePattern: '6########' },
  MQ: { name: 'Martinique', locale: 'fr', phonePrefix: '+596', phonePattern: '6########' },
  RE: { name: 'Réunion', locale: 'fr', phonePrefix: '+262', phonePattern: '6########' },
  GF: { name: 'French Guiana', locale: 'fr', phonePrefix: '+594', phonePattern: '6########' },
  NC: { name: 'New Caledonia', locale: 'fr', phonePrefix: '+687', phonePattern: '######' },
  PF: { name: 'French Polynesia', locale: 'fr', phonePrefix: '+689', phonePattern: '########' },
  YT: { name: 'Mayotte', locale: 'fr', phonePrefix: '+262', phonePattern: '6########' },
  XK: { name: 'Kosovo', locale: 'sr_RS_latin', phonePrefix: '+383', phonePattern: '4########' },
}

export const supportedCountries = Object.keys(countryConfigs)
